### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by pratik0910** [Mo45/Rust-Server-Website-Template#11]
Hey there, do you have discord?
Currently, I'm using the template and want some changes
I would also like to work with you, thanks
Please visit https://www.siliconunion.org if you do

Regards,
Tricky

**Comment by Mo45** [comment]
Hello. Read [this](https://github.com/Mo45/Rust-Server-Website-Template#copyright).
**The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.**

This is the reason why you're seeing these notices above. So legally, these notices shouldn't be removed from the works/files in which they're found.

If you really need to remove copyright from your project page, become my patron on [Patreon](https://www.patreon.com/rustserversinfo) (Pro Tier or higher), and [contact me](https://me.gametranslation.net/) from your Patreon account.
