### ISSUE TITLE
Mail Sending

### ISSUE THREAD

**Issue by CokkocZateki** [Mo45/Rust-Server-Website-Template#14]
Trying to get the mail function working on V 2.1. However i use shared hosting and im not sure how to get PHP:mail to work. the codes ive tried using in the examples does nothing so im a bit stuck as to how to implement it.

Any assistances would be gladly appreciated

**Comment by Mo45** [comment]
Hello.

Read [PHPMailer](https://github.com/PHPMailer/PHPMailer) documentation.

You need to use something like this:

`<?php 
$mail = new PHPMailer\PHPMailer\PHPMailer();
if(isset($_POST['send_mail'])){
try {
    //Server settings
    $mail->SMTPDebug = 2;                                       // Enable verbose debug output
    $mail->isSMTP();                                            // Set mailer to use SMTP
    $mail->Host       = 'smtp.yourmail.tld';  // Specify main and backup SMTP servers
    $mail->SMTPAuth   = true;                                   // Enable SMTP authentication
    $mail->Username   = 'contact@yourmail.tld';                     // SMTP username
    $mail->Password   = 'password';                               // SMTP password
    $mail->SMTPSecure = 'ssl';                                  // Enable TLS encryption, `ssl` also accepted
    $mail->Port       = 465;                                   // TCP port to connect to
    $mail->SMTPDebug = 0;

    //Recipients
    $mail->setFrom('contact@ruster.site', 'Ruster.Site');
    $mail->addAddress('kirillkrasin@gmail.com', 'Kirill Krasin');     // Add a recipient
    // Content
    $mail->isHTML(true);                                  // Set email format to HTML
    $mail->Subject = 'New Message';
    $text = $_POST['sender_text'];
    $sender_name = $_POST['sender_name'];
    $sender_mail = $_POST['sender_email'];
    $mail->Body    = "<strong>" . $sender_name . "</strong> (" . $sender_mail . ")<br><hr>" . $text;
    $mail->AltBody =  $_POST['sender_text'];
    $mail->send();
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
}

;?>`

**Comment by Mo45** [comment]
If you still can't configure PHPMailer, [check this](https://gist.github.com/Mo45/58b46243edde7b7a5b173e357c960f10).
