### ISSUE TITLE
Server image

### ISSUE THREAD

**Issue by zeuskodisos** [Mo45/Rust-Server-Website-Template#18]
## Expected behavior
Considering there are 2 servers, they shouldn't both be using img/serverlogo.png - My 2nd server has a different server image but I can't show it because it will only use the source img/serverlogo.png

**Comment by Mo45** [comment]
Edit **includes.php**, on line #**53**:
`if(MODULE_SERVERS_V2 == "ON"){$s2_img = "img/YOUR_LOGO_FOR_SERVER.png";};//Remove PHP Notice in logs`
If you are using servers module v1 (for rust-servers,info), on line #**56**:
```
if ($s2_img == "") {$s2_img = "img/YOUR_LOGO_FOR_SERVER.png";};//Empty path fix
		if (getimagesize($s2_img) == false) {$s2_img = "img/YOUR_LOGO_FOR_SERVER.png";};
```
