### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by xcoryakx** [Mo45/Rust-Server-Website-Template#20]
Join our Discord Server

Warning: include_once(paid/discord.php): failed to open stream: No such file or directory in /home/xxxx/public_html/Rust-Server-Website-Template-master/modules/discord.php on line 4

Warning: include_once(): Failed opening 'paid/discord.php' for inclusion (include_path='.:/opt/cpanel/ea-php73/root/usr/share/pear') in /home/xxxx/public_html/Rust-Server-Website-Template-master/modules/discord.php on line 4
4

What do i need to do.
![discord](https://user-images.githubusercontent.com/8308186/70385825-7e981780-1956-11ea-9b82-a9d95f5455e3.png)

**Comment by Mo45** [comment]
You are trying to use **paid** module. It is **not included** in GitHub release, and avaliable only for [Patrons](https://www.patreon.com/bePatron?u=8929240) with Supporter Level 2 or higher.
