### ISSUE TITLE
request SSL functionality 

### ISSUE THREAD

**Issue by slaapzak** [Mo45/Rust-Server-Website-Template#22]
## Expected behavior
set ssl on site
## Actual behavior
layout gets destroyed because of external links (please include everything in zip if possible)
## Steps to reproduce the problem
add ssl to site :-)

**Comment by Mo45** [comment]
This is **NOT** template issue. [Already work fine](https://rust.krasin.space/) with **https** same as with http.
Check:
`define( "SITE_URL" , "https://demo.ruster.site" );`
in your **config.php**
