### ISSUE TITLE
discord info 

### ISSUE THREAD

**Issue by Koolman2019** [Mo45/Rust-Server-Website-Template#23]
hello i can not get my discord info about players in discord to go any hire than 101 i have 1087 members but it will not show it 

Thank You 
Warkingz

**Comment by Mo45** [comment]
I don't understand what do you mean. By default You can only show online users count. Members count are included in paid module for my Patrons. Also, max number of members are limited up to 1000

**Comment by Koolman2019** [comment]
<img width="860" alt="dc" src="https://user-images.githubusercontent.com/49211153/80274513-def3df80-86d2-11ea-9439-c261736b6554.png">
sorry mate this bit i was talking about it only shows a max of 101 but there is over 1000 users

**Comment by Mo45** [comment]
Discord Widget API show limited count of online members (0-99).

**Comment by Koolman2019** [comment]
ok mate thank you so i can not change this
