### ISSUE TITLE
2 sites on server 1 discord does not work

### ISSUE THREAD

**Issue by slaapzak** [Mo45/Rust-Server-Website-Template#24]
## Expected behavior
discord show members
## Actual behavior
Join our Discord Server
MEMBERS
0USERS ONLINE

## Steps to reproduce the problem

On 1 website discord members works fine. on the other website discord doesn't work. both sites are on the same webserver. i got the discord link correct and ID.

**Comment by Mo45** [comment]
Template is working fine. Check your logs for more information.

**Comment by slaapzak** [comment]
Could you tell me which logs? I am 100% sure the settings on the config are
correct

Op ma 18 mei 2020 14:00 schreef Kirill Krasin <notifications@github.com>:

**Comment by Mo45** [comment]
> Could you tell me which logs? I am 100% sure the settings on the config are correct

Your web-server Apache/Nginx (logs) for your vhost (domain). Read them and find what is wrong.

**Comment by slaapzak** [comment]
Than i need to check iis logs. Running on that

Op di 19 mei 2020 10:27 schreef Kirill Krasin <notifications@github.com>:
