### ISSUE TITLE
$discord_total not displayed

### ISSUE THREAD

**Issue by twilliams1615** [Mo45/Rust-Server-Website-Template#26]
## Expected behavior
In the Discord Section, it will display total members, and Users Online
## Actual behavior
The $discord_total (discord.php line 13) does not seem to be defined/calculated anywhere. Currently, I am not seeing any number listed above "MEMBERS".
Attaching picture of what I see... 
![discord](https://user-images.githubusercontent.com/3835804/87209290-f8222a80-c2d6-11ea-8107-1ac2876d063a.PNG)

**Comment by Mo45** [comment]
Read comment on line **10** and line **21**

**Comment by twilliams1615** [comment]
Apologies. I thought that was referring to paid version of discord (nitro). Thanks.,
