### ISSUE TITLE
Stylesheet is missing

### ISSUE THREAD

**Issue by slicktop15** [Mo45/Rust-Server-Website-Template#29]
I'm trying to add version 2.4 to WordPress templates and it says the stylesheet is missing.

**Comment by Mo45** [comment]
This is PHP/CSS template, not WordPress template. [Difference ](https://github.com/Mo45/Rust-Server-Website-Template/compare/v2.3...v2.4)between 2.3 and 2.4 in Steam Auth and Feedback to Discord modules.
