### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by jwalte201** [Mo45/Rust-Server-Website-Template#3]
## Expected behavior
should import json data from https://api.rust-servers.info/info/1005 to be parsed by the includes.php file and show server status information.

## Actual behavior
Warning: file_get_contents(https://api.rust-servers.info/info/1005): failed to open stream: Network is unreachable in /srv/disk1/2593856/www/seattlerust.com/includes.php on line 7

## Steps to reproduce the problem
Here is a copy of my includes.php file. I bypassed the server ID variable from the config and just hard coded it in the includes file for the sake of troubleshooting, but it functions the same with both variable and hard coded link. I also included a screenshot of what I am seeing when I load the website (from multiple browsers and devices). have verified that the rust-servers.info website does show the server as online, and I can call the json data directly if I enter the URL into my browser (https://api.rust-servers.info/info/1005)

[includes.zip](https://github.com/Mo45/Rust-Server-Website-Template/files/1757084/includes.zip)

**Comment by Mo45** [comment]
You **do not need** to edit **inlcludes.php** or other parts of the script. The script works, it is checked repeatedly. Most likely your server (hosting) blocks outgoing connections?

**Comment by jwalte201** [comment]
this was the exact problem. I found that awardspace gives access to firewall settings, as soon as I unblocked outgoing connections, this resolved it. Thank you
