### ISSUE TITLE
Incorrect Fix?

### ISSUE THREAD

**Issue by ca-cdn** [Mo45/Rust-Server-Website-Template#32]
## Expected behavior
```
$s2_name = $parsed_json['name'];
    if ($s2_name == '') {
        $s2_name = 'Server Offline';
    }; //Offline server name fix
```
## Actual behavior
Does not fix other un-initialised array values such as
**Trying to access array offset on value of type null in \includes.php on line 58**
It might be more reliable and more efficient to simply check if the json array has any value at all.
if(empty($parsed_json)){
// create manually variables eg 
//$s2_name = $parsed_json['name'];
$s2_name = Server Offline;
$s2_status = 0;
} else {
your other code for when the json array is not empty
}

**Comment by Mo45** [comment]
Fix was not so efficient, but it work =)
Due to different API types inlcludes.php are very messy. I think i will make more module way to use Rust-Servers.Info & Rust-Servers.net API's
