### ISSUE TITLE
Little problem

### ISSUE THREAD

**Issue by Maxqc88** [Mo45/Rust-Server-Website-Template#33]
Since I changed my domain name everything remains at 0 (https://prnt.sc/wgktth)  I tried everything I even start to 0 for a blank file and remains still 0. Can you help me with this? Thanks

**Comment by Mo45** [comment]
Check your error logs.

**Comment by Maxqc88** [comment]
It's all good I don't know what happened but I think it had something to do with my host, I reinstalled my host to zero and everything came back! You can close this issue sorry for that.
