### ISSUE TITLE
Discord API key failure with module

### ISSUE THREAD

**Issue by Wuslor** [Mo45/Rust-Server-Website-Template#35]
## Expected behavior
In the Discord Configuration i have to add my API Key for the Discord Channel

## Actual behavior
Warning: include_once(paid/discord.php): failed to open stream: No such file or directory in /www/htdocs/v032973/rust/modules/discord.php on line 4

Warning: include_once(): Failed opening 'paid/discord.php' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/v032973/rust/modules/discord.php on line 4

Warning
: Invalid argument supplied for foreach() in
/www/htdocs/v032973/rust/modules/discord.php
on line
33

**Comment by Mo45** [comment]
You need to be my [paton](https://www.patreon.com/kirillkrasin) to use paid/discord.php module.

> Warning: include_once(paid/discord.php): failed to open stream: No such file or directory
