### ISSUE TITLE
after changing discordhook.

### ISSUE THREAD

**Issue by revolve75** [Mo45/Rust-Server-Website-Template#37]
Join our Discord Server

Warning: include_once(paid/discord.php): failed to open stream: No such file or directory in C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php on line 4

Warning: include_once(): Failed opening 'paid/discord.php' for inclusion (include_path='C:\Users\Donald\Documents\xamp\php\PEAR') in C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php on line 4

Notice: Undefined variable: discord_total in C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php on line 13
MEMBERS

Warning: count(): Parameter must be an array or an object that implements Countable in C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php on line 17

Warning: count(): Parameter must be an array or an object that implements Countable in C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php on line 17
0USERS ONLINE

Warning
: Invalid argument supplied for foreach() in
C:\Users\Donald\Documents\xamp\htdocs\rust\modules\discord.php
on line
33

**Comment by Mo45** [comment]
You need to be my [paton](https://www.patreon.com/kirillkrasin) to use paid/discord.php module.

> Warning: include_once(paid/discord.php): failed to open stream: No such file or directory
