### ISSUE TITLE
Hamburger menu not working

### ISSUE THREAD

**Issue by wrecktify** [Mo45/Rust-Server-Website-Template#40]
## Expected behavior
When website width is not wide enough the menu shrinks to a hamburger menu.  Should be able to click the hamburger menu.

## Actual behavior
Clicking the hamburger menu does nothing.

## Steps to reproduce the problem
Reduce width of website then try to click on hamburger menu.  Tested with Edge & Firefox latest versions.

**Comment by Mo45** [comment]
> Where can I get the paid discord module?
[Here](https://www.patreon.com/bePatron?u=8929240).
