### ISSUE TITLE
Error 500 on DigitalOcean??

### ISSUE THREAD

**Issue by justIeo** [Mo45/Rust-Server-Website-Template#41]
## Expected behavior
The site will redirect to the index.php page.
## Actual behavior
The site returns a HTTP Error 500.
## Steps to reproduce the problem
1. Set up an Apache server and transfer the site files into it.
2. Restart the Apache server and attempt to visit the site.

**Comment by justIeo** [comment]
I closed this because I wasn't using the stable version, but now I did use the stable version and I am still getting a 500 error.

**Comment by Mo45** [comment]
Demo site is runing on DigitalOcean droplet without any problems. Check your apache logs.
