### ISSUE TITLE
Trying to access offset on value of type null?

### ISSUE THREAD

**Issue by PGamingHD** [Mo45/Rust-Server-Website-Template#43]
## Expected behavior

Anyone got a fix for the issue that I posted a pic of below? Expected it to work without this showing up.

## Actual behavior

Showing up some weird errors ontop of the page shown below.

## Steps to reproduce the problem

Picture:

![image](https://user-images.githubusercontent.com/43955663/147410569-340e888c-098f-4ba5-81a4-b7528fbffda5.png)

**Comment by Mo45** [comment]
Which PHP version do you use?

**Comment by PGamingHD** [comment]
I like the error reporting, but ehh latest I think?

**Comment by Mo45** [comment]
Code is **[working ](https://rust.krasin.space/)fine**. Check your Apache error log, not notices. Also re-check your config.

**Comment by PGamingHD** [comment]
Other than me not adding a website link yet there shouldn't be any issues, the apache logs give the exact same error lol
