### ISSUE TITLE
images dont load Etc..

### ISSUE THREAD

**Issue by SkyRonic12** [Mo45/Rust-Server-Website-Template#49]
## Steps to reproduce the problem: Upload the template to almost any Panel, CyberPanel Etc..

![Screenshot 2024-02-27 183556](https://github.com/Mo45/Rust-Server-Website-Template/assets/90112438/b650c6c6-dae0-4111-9698-487b2337cd34)

**Comment by Mo45** [comment]
File permission issue or wrong stylesheet link.
