### ISSUE TITLE
Community memberCount

### ISSUE THREAD

**Issue by tomashakl** [Mo45/Rust-Server-Website-Template#5]
**Until today was everything all right. But at one time stop working memberCount. Do you know why?**

[czechrustservers.4fan.cz-php_error.log](https://github.com/Mo45/Rust-Server-Website-Template/files/2641809/czechrustservers.4fan.cz-php_error.log)

![image](https://user-images.githubusercontent.com/45081021/49410062-7dd90e00-f763-11e8-8689-68a3012878d5.png)

**Comment by Mo45** [comment]
Have you edited the code of the **includes.php** or **modules/community.php** files?

**Comment by tomashakl** [comment]
My provider argued that is error in your app. But if I change hosting everything is all all right. Thank you
http://czechrustservers.cz/
