### ISSUE TITLE
What might have causes this error?

### ISSUE THREAD

**Issue by BloodyMikey** [Mo45/Rust-Server-Website-Template#6]
<b>Warning</b>:  getimagesize(https://prnt.sc/lxte4k): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 in <b>C:\xampp\htdocs\includes.php</b> on line <b>17</b><br>

**Comment by Mo45** [comment]
https://prnt.sc/lxte4k - is not **image** url.
Function getimagesize — Get the size of an image, not an URL.
