### ISSUE TITLE
Show that server offline.

### ISSUE THREAD

**Issue by mostras20** [Mo45/Rust-Server-Website-Template#7]
## Expected behavior
To show server information and connect to the server button
## Actual behavior
Everything's done by the manual, doesen't work even in the demo page: https://me.gametranslation.net/rust
## Steps to reproduce the problem
Do an alternative way to show server information

**Comment by Mo45** [comment]
Rust-Servers.Info API is currently down. Contact current website [here](https://rust-servers.info/contacts.html).
